# [↩️ 리스트로 돌아가기](https://dacon.io/competitions/open/235698/overview/description)

# 셀을 실행할 때 팝업이 뜨면 `무시하고 계속하기` 를 눌러주세요

## 데이터 다운로드
---
아래 셀을 실행시켜 데이터를 colab 에 불러옵니다.
셀 실행은 Ctrl + Enter 를 이용해 실행시킬 수 있습니다.

In [1]:
# 데이터 다운로드 링크로 데이터를 코랩에 불러옵니다.

!wget 'https://bit.ly/3i4n1QB'

import zipfile
with zipfile.ZipFile('3i4n1QB', 'r') as existing_zip:
    existing_zip.extractall('data')

--2023-06-15 06:44:27--  https://bit.ly/3i4n1QB
Resolving bit.ly (bit.ly)... 67.199.248.10, 67.199.248.11
Connecting to bit.ly (bit.ly)|67.199.248.10|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://drive.google.com/uc?export=download&id=1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw [following]
--2023-06-15 06:44:27--  https://drive.google.com/uc?export=download&id=1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw
Resolving drive.google.com (drive.google.com)... 142.251.167.138, 142.251.167.100, 142.251.167.101, ...
Connecting to drive.google.com (drive.google.com)|142.251.167.138|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-10-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/77jovfs9ambg9eb1i3ll7hpr112604jk/1686811425000/17946651057176172524/*/1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw?e=download&uuid=c3bba766-7c99-4129-98d1-f87f5798a084 [following]
Warning: wildcards not supported in HTTP.
--2023-06-15 06:44:28--  https://doc-10-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/77jovfs9ambg9eb1i3ll7hpr112604jk/1686811425000/17946651057176172524/*/1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw?e=download&uuid=c3bba766-7c99-4129-98d1-f87f5798a084
Resolving doc-10-10-docs.googleusercontent.com (doc-10-10-docs.googleusercontent.com)... 142.251.163.132, 2607:f8b0:4004:c1b::84
Connecting to doc-10-10-docs.googleusercontent.com (doc-10-10-docs.googleusercontent.com)|142.251.163.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 137694 (134K) [application/zip]
Saving to: ‘3i4n1QB’

3i4n1QB             100%[===================>] 134.47K  --.-KB/s    in 0.02s

2023-06-15 06:44:28 (7.42 MB/s) - ‘3i4n1QB’ saved [137694/137694]

In [2]:
# 라이브러리 불러오기
import seaborn as sns
import pandas as pd

# VIF기능을 제공하는 라이브러리 불러오기
from statsmodels.stats.outliers_influence import variance_inflation_factor

# sklearn 의 MinMaxScaler 라이브러리 불러오기
from sklearn.preprocessing import MinMaxScaler

In [3]:
train = pd.read_csv('data/train.csv')

# 범주형 변수 제거(type)
train.drop('type',inplace = True,axis=1)

## 👋 실습
---
1. train 데이터의 VIF 계수를 출력해 봅니다.
2. MinMaxScaler를 통해 train의 수치데이터들을 변환 시켜 봅니다.
3. 변환된 train 데이터의 VIF 계수를 출력해 이전과 비교해 봅니다.

In [10]:
# train 데이터의 VIF 계수 출력
vif = pd.DataFrame()
vif['vif'] = [variance_inflation_factor(train.values,i) for i in range(train.shape[1])]
vif['feature'] = train.columns
vif

           vif               feature
0     4.007175                 index
1    64.107432               quality
2    59.149187         fixed acidity
3     9.610687      volatile acidity
4     9.273444           citric acid
5     3.616414        residual sugar
6     5.715981             chlorides
7     8.420883   free sulfur dioxide
8    14.833789  total sulfur dioxide
9   945.323991               density
10  583.501187                    pH
11   18.535850             sulphates
12  131.126700               alcohol

In [12]:
# MinMaxScaler를 통해 변수 변환

# MinMaxScaler를 "scaler"라는 변수에 지정해 봅시다.
scaler = MinMaxScaler()
# "scaler"를 train 으로 학습시켜주세요
scaler.fit(train)
# "scaler"를 통해 train의 수치들을 변환 시키고 train_scale에 저장 해 주세요.
train_scale = scaler.transform(train)

In [13]:
# Sclaer 를 통해 변환된 데이터의 VIF 확인
new_train_df =  pd.DataFrame(train_scale)

new_train_df.columns = train.columns



vif = pd.DataFrame()

vif["VIF Factor"] = [variance_inflation_factor(new_train_df.values, i) for i in range(new_train_df.shape[1])]

vif["features"] = new_train_df.columns

vif

    VIF Factor              features
0     3.848628                 index
1    14.491571               quality
2    37.792930         fixed acidity
3     6.978592      volatile acidity
4     9.094026           citric acid
5    14.246815        residual sugar
6     4.590877             chlorides
7     8.009056   free sulfur dioxide
8    11.227393  total sulfur dioxide
9   106.041429               density
10   23.477330                    pH
11    8.249344             sulphates
12   22.504171               alcohol

## 정답
---

In [14]:
# train 데이터의 VIF 계수 출력

vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(train.values, i) for i in range(train.shape[1])]
vif["features"] = train.columns
vif

    VIF Factor              features
0     4.007175                 index
1    64.107432               quality
2    59.149187         fixed acidity
3     9.610687      volatile acidity
4     9.273444           citric acid
5     3.616414        residual sugar
6     5.715981             chlorides
7     8.420883   free sulfur dioxide
8    14.833789  total sulfur dioxide
9   945.323991               density
10  583.501187                    pH
11   18.535850             sulphates
12  131.126700               alcohol

In [15]:
# MinMaxScaler를 통해 변수 변환

# MinMaxScaler를 "scaler"라는 변수에 지정해 봅시다.

scaler = MinMaxScaler()

# "scaler"를 train 으로 학습시켜주세요

scaler.fit(train)

# "scaler"를 통해 train의 수치들을 변환 시키고 train_scale에 저장 해 주세요.

train_scale = scaler.transform(train)

In [16]:
# Sclaer 를 통해 변환된 데이터의 VIF 확인

new_train_df =  pd.DataFrame(train_scale)
new_train_df.columns = train.columns

vif = pd.DataFrame()
vif["VIF Factor"] = [variance_inflation_factor(new_train_df.values, i) for i in range(new_train_df.shape[1])]
vif["features"] = new_train_df.columns
vif

    VIF Factor              features
0     3.848628                 index
1    14.491571               quality
2    37.792930         fixed acidity
3     6.978592      volatile acidity
4     9.094026           citric acid
5    14.246815        residual sugar
6     4.590877             chlorides
7     8.009056   free sulfur dioxide
8    11.227393  total sulfur dioxide
9   106.041429               density
10   23.477330                    pH
11    8.249344             sulphates
12   22.504171               alcohol

# [↩️ 리스트로 돌아가기](https://dacon.io/competitions/open/235698/overview/description)