# [‚Ü©Ô∏è Î¶¨Ïä§Ìä∏Î°ú ÎèåÏïÑÍ∞ÄÍ∏∞](https://dacon.io/competitions/open/235698/overview/description)

# ÏÖÄÏùÑ Ïã§ÌñâÌï† Îïå ÌåùÏóÖÏù¥ Îú®Î©¥ `Î¨¥ÏãúÌïòÍ≥† Í≥ÑÏÜçÌïòÍ∏∞` Î•º ÎàåÎü¨Ï£ºÏÑ∏Ïöî

## Îç∞Ïù¥ÌÑ∞ Îã§Ïö¥Î°úÎìú
---
ÏïÑÎûò ÏÖÄÏùÑ Ïã§ÌñâÏãúÏºú Îç∞Ïù¥ÌÑ∞Î•º colab Ïóê Î∂àÎü¨ÏòµÎãàÎã§.
ÏÖÄ Ïã§ÌñâÏùÄ Ctrl + Enter Î•º Ïù¥Ïö©Ìï¥ Ïã§ÌñâÏãúÌÇ¨ Ïàò ÏûàÏäµÎãàÎã§.

In [1]:
# Îç∞Ïù¥ÌÑ∞ Îã§Ïö¥Î°úÎìú ÎßÅÌÅ¨Î°ú Îç∞Ïù¥ÌÑ∞Î•º ÏΩîÎû©Ïóê Î∂àÎü¨ÏòµÎãàÎã§.

!wget 'https://bit.ly/3i4n1QB'

import zipfile
with zipfile.ZipFile('3i4n1QB', 'r') as existing_zip:
    existing_zip.extractall('data')

--2023-06-16 10:15:58--  https://bit.ly/3i4n1QB
Resolving bit.ly (bit.ly)... 67.199.248.11, 67.199.248.10
Connecting to bit.ly (bit.ly)|67.199.248.11|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://drive.google.com/uc?export=download&id=1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw [following]
--2023-06-16 10:15:58--  https://drive.google.com/uc?export=download&id=1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw
Resolving drive.google.com (drive.google.com)... 74.125.135.102, 74.125.135.113, 74.125.135.100, ...
Connecting to drive.google.com (drive.google.com)|74.125.135.102|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-10-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/cgcds7dbco2189j7o8q2ri49osujj0me/1686910500000/17946651057176172524/*/1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw?e=download&uuid=fe57d35d-eadf-435b-949a-1c246933ab98 [following]
Warning: wildcards not supported in HTTP.
--2023-06-16 10:15:59--  https://doc-10-10-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/cgcds7dbco2189j7o8q2ri49osujj0me/1686910500000/17946651057176172524/*/1emLrrpFWT8dCoj5BJb12-5QMG2-nruUw?e=download&uuid=fe57d35d-eadf-435b-949a-1c246933ab98
Resolving doc-10-10-docs.googleusercontent.com (doc-10-10-docs.googleusercontent.com)... 74.125.195.132, 2607:f8b0:400e:c09::84
Connecting to doc-10-10-docs.googleusercontent.com (doc-10-10-docs.googleusercontent.com)|74.125.195.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 137694 (134K) [application/zip]
Saving to: ‚Äò3i4n1QB‚Äô

3i4n1QB             100%[===================>] 134.47K  --.-KB/s    in 0.001s

2023-06-16 10:15:59 (104 MB/s) - ‚Äò3i4n1QB‚Äô saved [137694/137694]

In [2]:
# ÎùºÏù¥Î∏åÎü¨Î¶¨ Î∞è Îç∞Ïù¥ÌÑ∞ Î∂àÎü¨Ïò§Í∏∞
import pandas as pd

train = pd.read_csv('data/train.csv')

## üëã Ïã§Ïäµ
---

In [3]:
# train Îç∞Ïù¥ÌÑ∞ ÌôïÏù∏
train.head()

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white

In [4]:
# train Îç∞Ïù¥ÌÑ∞Ïùò pH Î≥ÄÏàòÎ•º Íµ¨Í∞ÑÏù¥ 4Í∞úÏù∏ Î≤îÏ£ºÌòï Î≥ÄÏàòÎ°ú Î≥ÄÌôò
# pH < 1  -> lowest
# 1<= pH < 2 -> low
# 2 <= pH < 3-> normal
# 3 <= pH -> high
def func(x):
    if x < 3:
        return 'lowest'
    elif x < 3.3:
        return 'low'
    elif x < 3.5:
        return 'normal'
    else :
        return'high'

train['pH'] = train['pH'].apply(lambda x : func(x))

In [5]:
# Î≥ÄÌôò ÌõÑ Îç∞Ïù¥ÌÑ∞ ÌôïÏù∏
train.head()

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,normal,0.44,10.2,white
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,low,0.59,9.5,red
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,low,0.52,10.9,white
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,low,0.50,10.8,white
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,low,0.43,10.9,white

## Ï†ïÎãµ

In [ ]:
# train Îç∞Ïù¥ÌÑ∞ ÌôïÏù∏
train.head()

In [ ]:
# train Îç∞Ïù¥ÌÑ∞Ïùò pH Î≥ÄÏàòÎ•º Íµ¨Í∞ÑÏù¥ 4Í∞úÏù∏ Î≤îÏ£ºÌòï Î≥ÄÏàòÎ°ú Î≥ÄÌôò
# pH < 1  -> lowest
# 1<= pH < 2 -> low
# 2 <= pH < 3-> normal
# 3 <= pH -> high

def func(x):
    if x < 3:
        return 'lowest'
    elif x < 3.3:
        return 'low'
    elif x < 3.5:
        return 'normal'
    else :
        return'high'

train['pH'] = train['pH'].apply(lambda x : func(x))

In [ ]:
# Î≥ÄÌôò ÌõÑ Îç∞Ïù¥ÌÑ∞ ÌôïÏù∏
train.head()

# [‚Ü©Ô∏è Î¶¨Ïä§Ìä∏Î°ú ÎèåÏïÑÍ∞ÄÍ∏∞](https://dacon.io/competitions/open/235698/overview/description)